{
 "title": "Business Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Predictions / sec",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trustpilot_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Predictions per Topic",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster_id) (trustpilot_cluster_predictions_total)",
     "legendFormat": "cluster{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Topic predictions Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(trustpilot_cluster_predictions_total[5m])",
     "legendFormat": "cluster{{cluster_id}}"
    }
   ]
  }
 ]
}