{
 "title": "Infrastructure Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "API Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m])\r\n/\r\nrate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests per endpoint",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}